version: '3.7'
services:

  redis-service:
    image: tobyhferguson/redis-microservices-demo_redis-service 
    ports:
      - "6379:6379"
    networks:
      - redis-microservices-network

  mysql-debezium-service:
    image: tobyhferguson/redis-microservices-demo_mysql-debezium-service
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - redis-microservices-network

  db-to-streams-service:
    image: tobyhferguson/redis-microservices-demo_db-to-streams-service
    ports:
      - "8082:8082"
    networks:
      - redis-microservices-network
    depends_on:
      - mysql-debezium-service
      - redis-service

  streams-to-redisgraph-service:
    image: tobyhferguson/redis-microservices-demo_streams-to-redisgraph-service
    ports:
      - "8083:8083"
    networks:
      - redis-microservices-network
    depends_on:
      - mysql-debezium-service
      - redis-service

  sql-rest-api:
    image: tobyhferguson/redis-microservices-demo_sql-rest-api
    ports:
      - "8081:8081"
    networks:
      - redis-microservices-network
    depends_on:
      - mysql-debezium-service

  caching-service:
    image: tobyhferguson/redis-microservices-demo_caching-service
    ports:
      - "8084:8084"
    networks:
      - redis-microservices-network
    depends_on:
      - mysql-debezium-service
      - redis-service

  streams-to-redisearch-service:
    image: tobyhferguson/redis-microservices-demo_streams-to-redisearch-service
    ports:
      - "8085:8085"
    networks:
      - redis-microservices-network
    depends_on:
      - redis-service

  comments-service:
    build:
      context: ./comments-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - redis-microservices-network
    depends_on:
      - redis-service
    restart: always

  front-end:
    image: tobyhferguson/redis-microservices-demo_front-end
    ports:
      - "80:80"
    networks:
      - redis-microservices-network
    depends_on:
      - redis-service
      - mysql-debezium-service
      - streams-to-redisgraph-service
      - streams-to-redisearch-service
      - db-to-streams-service
      - caching-service
      - sql-rest-api

networks:
  redis-microservices-network:
